// GroupPermission Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

// Get GroupPermissions
export const GET_GROUP_PERMISSIONS = "GET_GROUP_PERMISSIONS";
export const GET_MODERATOR_GROUP_PERMISSIONS = "GET_MODERATOR_GROUP_PERMISSIONS";

// Add GroupPermission
export const ADD_NEW_GROUP_PERMISSION = "ADD_NEW_GROUP_PERMISSION";
export const ADD_NEW_GROUP_PERMISSION_SUCCESS = "ADD_NEW_GROUP_PERMISSION_SUCCESS";
export const ADD_NEW_GROUP_PERMISSION_FAIL = "ADD_NEW_GROUP_PERMISSION_FAIL";

// Edit GroupPermission
export const UPDATE_GROUP_PERMISSION = "UPDATE_GROUP_PERMISSION";
export const UPDATE_GROUP_PERMISSION_SUCCESS = "UPDATE_GROUP_PERMISSION_SUCCESS";
export const UPDATE_GROUP_PERMISSION_FAIL = "UPDATE_GROUP_PERMISSION_FAIL";

// Delete GroupPermission
export const DELETE_GROUP_PERMISSION = "DELETE_GROUP_PERMISSION";
export const DELETE_GROUP_PERMISSION_SUCCESS = "DELETE_GROUP_PERMISSION_SUCCESS";
export const DELETE_GROUP_PERMISSION_FAIL = "DELETE_GROUP_PERMISSION_FAIL";
