// User Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

// Get Users
export const GET_USERS = "GET_USERS";
export const GET_USER_DETAILS = "GET_USER_DETAILS";

// Add User
export const ADD_NEW_USER = "ADD_NEW_USER";
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS";
export const ADD_NEW_USER_FAIL = "ADD_NEW_USER_FAIL";

// Edit User
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

// Change user PAssword
export const CHANGE_USER_PASSWORD = "CHANGE_USER_PASSWORD";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_FAIL = "CHANGE_USER_PASSWORD_FAIL";


// Delete User
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";


// Specific User(s)
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_MODERATOR_USERS = "GET_MODERATOR_USERS";
export const GET_CAMPAIGN_MODERATORS = "GET_CAMPAIGN_MODERATORS";
export const GET_CAMPAIGN_SORTERS = "GET_CAMPAIGN_SORTERS";

