# Generated by Django 4.2.2 on 2024-01-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_party'),
        ('elections', '0005_alter_electioncandidate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionpartycandidate',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_party_candidates', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='electionpartycandidate',
            name='election_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_candidate_elections', to='elections.electionparty'),
        ),
    ]
