# Generated by Django 4.2.2 on 2024-01-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_electioncommittee_election_committee_sorter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electioncommittee',
            old_name='election_committee_sorter',
            new_name='sorter',
        ),
    ]
