# Generated by Django 4.2.2 on 2024-01-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_remove_election_elect_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_method',
            field=models.CharField(blank=True, choices=[('candidateOnly', 'Candidate Only System'), ('partyOnly', 'Party Only System'), ('combinedPartyCandidate', 'Combined Candidate Party System'), ('proportionalRepresentationSystem', 'Proportional Representation System'), ('mixedElectoralSystem', 'Mixed Electoral System')], max_length=50, null=True, verbose_name='Election Type'),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_result',
            field=models.TextField(blank=True, choices=[('total', 'Total'), ('detailed', 'Detailed'), ('PVR', 'Party Voting Results'), ('IO', 'Individual Only')], max_length=50, null=True, verbose_name='Election Result Type'),
        ),
    ]
