# Generated by Django 4.2.2 on 2024-01-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_alter_electioncommitteeresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncommitteeresult',
            name='election_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_result_candidates', to='elections.electioncandidate'),
        ),
    ]
