// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_ALL_ELECTORS = "GET_ALL_ELECTORS";
export const GET_ELECTORS = "GET_ELECTORS";

// Add Elector
export const ADD_NEW_ELECTOR = "ADD_NEW_ELECTOR";
export const ADD_ELECTOR_SUCCESS = "ADD_ELECTOR_SUCCESS";
export const ADD_ELECTOR_FAIL = "ADD_ELECTOR_FAIL";

// Edit Elector
export const UPDATE_ELECTOR = "UPDATE_ELECTOR";
export const UPDATE_ELECTOR_SUCCESS = "UPDATE_ELECTOR_SUCCESS";
export const UPDATE_ELECTOR_FAIL = "UPDATE_ELECTOR_FAIL";

// Delete Elector
export const DELETE_ELECTOR = "DELETE_ELECTOR";
export const DELETE_ELECTOR_SUCCESS = "DELETE_ELECTOR_SUCCESS";
export const DELETE_ELECTOR_FAIL = "DELETE_ELECTOR_FAIL";
