# Generated by Django 4.2.2 on 2024-01-11 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_electionpartycandidate_candidate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0005_alter_campaignpartyguarantee_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignsorting',
            options={'permissions': [('canViewCampaignSorting', 'Can View Campaign Sorting'), ('canAddCampaignSorting', 'Can Add Campaign Sorting'), ('canChangeCampaignSorting', 'Can Change Campaign Sorting'), ('canDeleteCampaignSorting', 'Can Delete Campaign Sorting')], 'verbose_name': 'Campaign Sorting', 'verbose_name_plural': 'Campaign Sortings'},
        ),
        migrations.AlterField(
            model_name='campaignsorting',
            name='election_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_election_committees', to='elections.electioncommittee'),
        ),
        migrations.AlterField(
            model_name='campaignsorting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampaignPartySorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('election_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_election_committees', to='elections.electioncommittee')),
                ('election_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_party_sortings', to='elections.electionparty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Party Sorting',
                'verbose_name_plural': 'Campaign Party Sortings',
                'db_table': 'campaign_party_sorting',
                'permissions': [('canViewCampaignSorting', 'Can View Campaign Sorting'), ('canAddCampaignSorting', 'Can Add Campaign Sorting'), ('canChangeCampaignSorting', 'Can Change Campaign Sorting'), ('canDeleteCampaignSorting', 'Can Delete Campaign Sorting')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignPartyCandidateSorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('election_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_election_committees', to='elections.electioncommittee')),
                ('election_party_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_party_candidate_sortings', to='elections.electionpartycandidate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Party Candidate Sorting',
                'verbose_name_plural': 'Campaign Party Candidate Sortings',
                'db_table': 'campaign_party_candidate_sorting',
                'permissions': [('canViewCampaignSorting', 'Can View Campaign Sorting'), ('canAddCampaignSorting', 'Can Add Campaign Sorting'), ('canChangeCampaignSorting', 'Can Change Campaign Sorting'), ('canDeleteCampaignSorting', 'Can Delete Campaign Sorting')],
                'abstract': False,
            },
        ),
    ]
