# Generated by Django 4.2.2 on 2024-01-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_campaign_candidate_campaign_campaign_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_type',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),

    ]
