# Generated by Django 4.2.2 on 2024-01-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_entity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='entity_id',
            new_name='object_id',
        ),
    ]
