# Generated by Django 4.2.2 on 2024-01-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_electionsorting_electionpartysorting'),
        ('campaigns', '0013_campaign_campaign_type_campaign_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpartycandidatesorting',
            name='election_party_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_election_party_candidate_sortings', to='elections.electionpartycandidate'),
        ),
        migrations.AlterField(
            model_name='campaignsorting',
            name='election_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_election_candidate_sortings', to='elections.electioncandidate'),
        ),
    ]
