# Generated by Django 4.2.2 on 2024-01-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_remove_election_elect_result_and_more'),
        ('campaigns', '0014_alter_campaignpartycandidatesorting_election_party_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpartycandidatesorting',
            name='election_party_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_party_candidate_sortings', to='elections.electionpartycandidate'),
        ),
        migrations.AlterField(
            model_name='campaignpartysorting',
            name='election_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_party_sortings', to='elections.electionparty'),
        ),
        migrations.AlterField(
            model_name='campaignsorting',
            name='election_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_candidate_sortings', to='elections.electioncandidate'),
        ),
    ]
