# Generated by Django 4.2.2 on 2024-01-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_campaign_party_campaignpartymember_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignpartyguarantee',
            old_name='campaign_party',
            new_name='campaign',
        ),
    ]
