# Generated by Django 4.2.2 on 2024-01-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_campaign_party_campaignpartyguarantee_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpartyguarantee',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_party_guarantee_guarantors', to='campaigns.campaignpartymember'),
        ),
    ]
