# Generated by Django 4.2.2 on 2024-01-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_electionpartycandidate_candidate_and_more'),
        ('campaigns', '0006_alter_campaignsorting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.electioncandidate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_party',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.electionparty'),
        ),
    ]
