# Generated by Django 4.2.2 on 2024-01-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_rename_content_type_campaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='entity_id',
            field=models.PositiveIntegerField(default=193),
            preserve_default=False,
        ),
    ]
