# Generated by Django 4.2.2 on 2024-01-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_rename_entity_id_campaign_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='object_id',
        ),
    ]
