# Generated by Django 4.2.2 on 2024-03-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '__first__'),
        ('campaigns', '0015_alter_campaignpartycandidatesorting_election_party_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignattendee',
            name='civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elector_attendees', to='voters.voter'),
        ),
        migrations.AlterField(
            model_name='campaignguarantee',
            name='civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_elector_guarantees', to='voters.voter'),
        ),
        migrations.AlterField(
            model_name='campaignpartyguarantee',
            name='civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_party_elector_guarantees', to='voters.voter'),
        ),
    ]
