// Candidate Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Get Candidates
export const GET_CANDIDATES = "GET_CANDIDATES";

// Add Candidate
export const ADD_NEW_CANDIDATE = "ADD_NEW_CANDIDATE";
export const ADD_NEW_CANDIDATE_SUCCESS = "ADD_NEW_CANDIDATE_SUCCESS";
export const ADD_NEW_CANDIDATE_FAIL = "ADD_NEW_CANDIDATE_FAIL";

// Edit Candidate
export const UPDATE_CANDIDATE = "UPDATE_CANDIDATE";
export const UPDATE_CANDIDATE_SUCCESS = "UPDATE_CANDIDATE_SUCCESS";
export const UPDATE_CANDIDATE_FAIL = "UPDATE_CANDIDATE_FAIL";

// Delete Candidate
export const DELETE_CANDIDATE = "DELETE_CANDIDATE";
export const DELETE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_FAIL = "DELETE_CANDIDATE_FAIL";

// Candidate Details
export const GET_CANDIDATE_DETAILS = "GET_CANDIDATE_DETAILS";

