// Election Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

// Elections
export const GET_ELECTIONS = "GET_ELECTIONS";
export const GET_ELECTION_DETAILS = "GET_ELECTION_DETAILS";
export const UPLOAD_ELECTION_DATA = "UPLOAD_ELECTION_DATA";
export const GET_PUBLIC_ELECTIONS = "GET_PUBLIC_ELECTIONS";

// Add Election
export const ADD_ELECTION = "ADD_ELECTION";
export const ADD_ELECTION_SUCCESS = "ADD_ELECTION_SUCCESS";
export const ADD_ELECTION_FAIL = "ADD_ELECTION_FAIL";

// Edit Election
export const UPDATE_ELECTION = "UPDATE_ELECTION";
export const UPDATE_ELECTION_SUCCESS = "UPDATE_ELECTION_SUCCESS";
export const UPDATE_ELECTION_FAIL = "UPDATE_ELECTION_FAIL";

// Delete Election
export const DELETE_ELECTION = "DELETE_ELECTION";
export const DELETE_ELECTION_SUCCESS = "DELETE_ELECTION_SUCCESS";
export const DELETE_ELECTION_FAIL = "DELETE_ELECTION_FAIL";

// Election Candidates
export const GET_ELECTION_CANDIDATES = "GET_ELECTION_CANDIDATES";
export const GET_ELECTION_CANDIDATES_SUCCESS = "GET_ELECTION_CANDIDATES_SUCCESS";
export const GET_ELECTION_CANDIDATES_FAIL = "GET_ELECTION_CANDIDATES_FAIL";

// Add Election Candidate
export const ADD_NEW_ELECTION_CANDIDATE = "ADD_NEW_ELECTION_CANDIDATE";
export const ADD_ELECTION_CANDIDATE_SUCCESS = "ADD_ELECTION_CANDIDATE_SUCCESS";
export const ADD_TO_ELECTION_AFTER_CANDIDATE_SUCCESS = "ADD_TO_ELECTION_AFTER_CANDIDATE_SUCCESS";
export const ADD_ELECTION_CANDIDATE_FAIL = "ADD_ELECTION_CANDIDATE_FAIL";

// Edit Election Candidate
export const UPDATE_ELECTION_CANDIDATE = "UPDATE_ELECTION_CANDIDATE";
export const UPDATE_ELECTION_CANDIDATE_SUCCESS = "UPDATE_ELECTION_CANDIDATE_SUCCESS";
export const UPDATE_ELECTION_CANDIDATE_FAIL = "UPDATE_ELECTION_CANDIDATE_FAIL";

// Delete Election Candidate
export const DELETE_ELECTION_CANDIDATE = "DELETE_ELECTION_CANDIDATE";
export const DELETE_ELECTION_CANDIDATE_SUCCESS = "DELETE_ELECTION_CANDIDATE_SUCCESS";
export const DELETE_ELECTION_CANDIDATE_FAIL = "DELETE_ELECTION_CANDIDATE_FAIL";

// Update Election Candidate Votes
export const UPDATE_ELECTION_CANDIDATE_VOTES = "UPDATE_ELECTION_CANDIDATE_VOTES";
export const UPDATE_ELECTION_CANDIDATE_VOTES_SUCCESS = "UPDATE_ELECTION_CANDIDATE_VOTES_SUCCESS";
export const UPDATE_ELECTION_CANDIDATE_VOTES_FAIL = "UPDATE_ELECTION_CANDIDATE_VOTES_FAIL";


// Election Party
export const GET_ELECTION_PARTIES = "GET_ELECTION_PARTIES";
export const GET_ELECTION_PARTIES_SUCCESS = "GET_ELECTION_PARTIES_SUCCESS";
export const GET_ELECTION_PARTIES_FAIL = "GET_ELECTION_PARTIES_FAIL";

// Add Election party
export const ADD_ELECTION_PARTY = "ADD_ELECTION_PARTY";
export const ADD_ELECTION_PARTY_SUCCESS = "ADD_ELECTION_PARTY_SUCCESS";
export const ADD_TO_ELECTION_AFTER_PARTY_SUCCESS = "ADD_TO_ELECTION_AFTER_PARTY_SUCCESS";
export const ADD_ELECTION_PARTY_FAIL = "ADD_ELECTION_PARTY_FAIL";

// Delete Election Party
export const DELETE_ELECTION_PARTY = "DELETE_ELECTION_PARTY";
export const DELETE_ELECTION_PARTY_SUCCESS = "DELETE_ELECTION_PARTY_SUCCESS";
export const DELETE_ELECTION_PARTY_FAIL = "DELETE_ELECTION_PARTY_FAIL";

// Update Election Party
export const UPDATE_ELECTION_PARTY = "UPDATE_ELECTION_PARTY";
export const UPDATE_ELECTION_PARTY_SUCCESS = "UPDATE_ELECTION_PARTY_SUCCESS";
export const UPDATE_ELECTION_PARTY_FAIL = "UPDATE_ELECTION_PARTY_FAIL";


// Election Party Candidates ---
export const GET_ELECTION_PARTY_CANDIDATES = "GET_ELECTION_PARTY_CANDIDATES";
export const GET_ELECTION_PARTY_CANDIDATES_SUCCESS = "GET_ELECTION_PARTY_CANDIDATES_SUCCESS";
export const GET_ELECTION_PARTY_CANDIDATES_FAIL = "GET_ELECTION_PARTY_CANDIDATES_FAIL";

// Add Election Party Candidate
export const ADD_ELECTION_PARTY_CANDIDATE = "ADD_ELECTION_PARTY_CANDIDATE";
export const ADD_ELECTION_PARTY_CANDIDATE_SUCCESS = "ADD_ELECTION_PARTY_CANDIDATE_SUCCESS";
export const ADD_TO_ELECTION_AFTER_PARTY_CANDIDATE_SUCCESS = "ADD_TO_ELECTION_AFTER_PARTY_CANDIDATE_SUCCESS";
export const ADD_ELECTION_PARTY_CANDIDATE_FAIL = "ADD_ELECTION_PARTY_CANDIDATE_FAIL";

// Delete Election Party Candidate
export const DELETE_ELECTION_PARTY_CANDIDATE = "DELETE_ELECTION_PARTY_CANDIDATE";
export const DELETE_ELECTION_PARTY_CANDIDATE_SUCCESS = "DELETE_ELECTION_PARTY_CANDIDATE_SUCCESS";
export const DELETE_ELECTION_PARTY_CANDIDATE_FAIL = "DELETE_ELECTION_PARTY_CANDIDATE_FAIL";

// Update Election Candidate Votes
export const UPDATE_ELECTION_PARTY_CANDIDATE = "UPDATE_ELECTION_PARTY_CANDIDATE";
export const UPDATE_ELECTION_PARTY_CANDIDATE_SUCCESS = "UPDATE_ELECTION_PARTY_CANDIDATE_SUCCESS";
export const UPDATE_ELECTION_PARTY_CANDIDATE_FAIL = "UPDATE_ELECTION_PARTY_CANDIDATE_FAIL";

// Update Election Candidate Votes
export const UPDATE_ELECTION_PARTY_CANDIDATE_VOTES = "UPDATE_ELECTION_PARTY_CANDIDATE_VOTES";
export const UPDATE_ELECTION_PARTY_CANDIDATE_VOTES_SUCCESS = "UPDATE_ELECTION_PARTY_CANDIDATE_VOTES_SUCCESS";
export const UPDATE_ELECTION_PARTY_CANDIDATE_VOTES_FAIL = "UPDATE_ELECTION_PARTY_CANDIDATE_VOTES_FAIL";


// Election Committees
export const GET_ELECTION_COMMITTEES = "GET_ELECTION_COMMITTEES";
export const GET_ELECTION_COMMITTEES_SUCCESS = "GET_ELECTION_COMMITTEES_SUCCESS";
export const GET_ELECTION_COMMITTEES_FAIL = "GET_ELECTION_COMMITTEES_FAIL";

// Add Election Committee
export const ADD_NEW_ELECTION_COMMITTEE = "ADD_NEW_ELECTION_COMMITTEE";
export const ADD_ELECTION_COMMITTEE_SUCCESS = "ADD_ELECTION_COMMITTEE_SUCCESS";
export const ADD_ELECTION_COMMITTEE_FAIL = "ADD_ELECTION_COMMITTEE_FAIL";

// Edit Election Committee
export const UPDATE_ELECTION_COMMITTEE = "UPDATE_ELECTION_COMMITTEE";
export const UPDATE_ELECTION_COMMITTEE_SUCCESS = "UPDATE_ELECTION_COMMITTEE_SUCCESS";
export const UPDATE_ELECTION_COMMITTEE_FAIL = "UPDATE_ELECTION_COMMITTEE_FAIL";

// Delete Election Committee
export const DELETE_ELECTION_COMMITTEE = "DELETE_ELECTION_COMMITTEE";
export const DELETE_ELECTION_COMMITTEE_SUCCESS = "DELETE_ELECTION_COMMITTEE_SUCCESS";
export const DELETE_ELECTION_COMMITTEE_FAIL = "DELETE_ELECTION_COMMITTEE_FAIL";


// Election Results
export const UPDATE_ELECTION_PARTY_RESULTS = "UPDATE_ELECTION_PARTY_RESULTS";
export const UPDATE_ELECTION_PARTY_RESULTS_SUCCESS = "UPDATE_ELECTION_PARTY_RESULTS_SUCCESS";
export const UPDATE_ELECTION_PARTY_RESULTS_FAIL = "UPDATE_ELECTION_PARTY_RESULTS_FAIL";

// Election Party  Results
export const UPDATE_ELECTION_PARTY_CANDIDATE_RESULTS = "UPDATE_ELECTION_RESULTS";
export const UPDATE_ELECTION_PARTY_CANDIDATE_RESULTS_SUCCESS = "UPDATE_ELECTION_PARTY_CANDIDATE_RESULTS_SUCCESS";
export const UPDATE_ELECTION_PARTY_CANDIDATE_RESULTS_FAIL = "UPDATE_ELECTION_PARTY_CANDIDATE_RESULTS_FAIL";

// Election Party Candidate Results
export const UPDATE_ELECTION_RESULTS = "UPDATE_ELECTION_RESULTS";
export const UPDATE_ELECTION_RESULTS_SUCCESS = "UPDATE_ELECTION_RESULTS_SUCCESS";
export const UPDATE_ELECTION_RESULTS_FAIL = "UPDATE_ELECTION_RESULTS_FAIL";



// Election Campaigns
export const GET_ELECTION_CAMPAIGNS = "GET_ELECTION_CAMPAIGNS";
export const GET_ELECTION_CAMPAIGNS_SUCCESS = "GET_ELECTION_CAMPAIGNS_SUCCESS";
export const GET_ELECTION_CAMPAIGNS_FAIL = "GET_ELECTION_CAMPAIGNS_FAIL";

// Add Election Campaign
export const ADD_NEW_ELECTION_CAMPAIGN = "ADD_NEW_ELECTION_CAMPAIGN";
export const ADD_ELECTION_CAMPAIGN_SUCCESS = "ADD_ELECTION_CAMPAIGN_SUCCESS";
export const ADD_ELECTION_CAMPAIGN_FAIL = "ADD_ELECTION_CAMPAIGN_FAIL";

// Edit Election Campaign
export const UPDATE_ELECTION_CAMPAIGN = "UPDATE_ELECTION_CAMPAIGN";
export const UPDATE_ELECTION_CAMPAIGN_SUCCESS = "UPDATE_ELECTION_CAMPAIGN_SUCCESS";
export const UPDATE_ELECTION_CAMPAIGN_FAIL = "UPDATE_ELECTION_CAMPAIGN_FAIL";

// Delete Election Campaign
export const DELETE_ELECTION_CAMPAIGN = "DELETE_ELECTION_CAMPAIGN";
export const DELETE_ELECTION_CAMPAIGN_SUCCESS = "DELETE_ELECTION_CAMPAIGN_SUCCESS";
export const DELETE_ELECTION_CAMPAIGN_FAIL = "DELETE_ELECTION_CAMPAIGN_FAIL";
