// Campaign Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Get Campaigns
export const GET_CAMPAIGNS = "GET_CAMPAIGNS";
export const GET_CAMPAIGN_COUNT = "GET_CAMPAIGN_COUNT";

// Add Campaign
export const ADD_NEW_CAMPAIGN = "ADD_NEW_CAMPAIGN";
export const ADD_NEW_CAMPAIGN_SUCCESS = "ADD_NEW_CAMPAIGN_SUCCESS";
export const ADD_NEW_CAMPAIGN_FAIL = "ADD_NEW_CAMPAIGN_FAIL";

// Edit Campaign
export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_FAIL = "UPDATE_CAMPAIGN_FAIL";

// Delete Campaign
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_FAIL = "DELETE_CAMPAIGN_FAIL";

// Campaign Details
export const GET_CAMPAIGN_DETAILS = "GET_CAMPAIGN_DETAILS";


// Campaign Members
// Campaign Members
export const GET_ALL_CAMPAIGN_MEMBERS = "GET_ALL_CAMPAIGN_MEMBERS";
export const GET_ALL_CAMPAIGN_MEMBERS_SUCCESS = "GET_ALL_CAMPAIGN_MEMBERS_SUCCESS";
export const GET_ALL_CAMPAIGN_MEMBERS_FAIL = "GET_ALL_CAMPAIGN_MEMBERS_FAIL";

// Add Campaign Member
export const ADD_NEW_CAMPAIGN_MEMBER = "ADD_NEW_CAMPAIGN_MEMBER";
export const ADD_NEW_CAMPAIGN_MEMBER_SUCCESS = "ADD_NEW_CAMPAIGN_MEMBER_SUCCESS";
export const ADD_NEW_CAMPAIGN_MEMBER_FAIL = "ADD_NEW_CAMPAIGN_MEMBER_FAIL";

// Edit Campaign Member
export const UPDATE_CAMPAIGN_MEMBER = "UPDATE_CAMPAIGN_MEMBER";
export const UPDATE_CAMPAIGN_MEMBER_SUCCESS = "UPDATE_CAMPAIGN_MEMBER_SUCCESS";
export const UPDATE_CAMPAIGN_MEMBER_FAIL = "UPDATE_CAMPAIGN_MEMBER_FAIL";

// Delete Campaign Member
export const DELETE_CAMPAIGN_MEMBER = "DELETE_CAMPAIGN_MEMBER";
export const DELETE_CAMPAIGN_MEMBER_SUCCESS = "DELETE_CAMPAIGN_MEMBER_SUCCESS";
export const DELETE_CAMPAIGN_MEMBER_FAIL = "DELETE_CAMPAIGN_MEMBER_FAIL";

// Campaign Member Details
export const GET_CAMPAIGN_MEMBER_DETAILS = "GET_CAMPAIGN_MEMBER_DETAILS";
export const GET_CAMPAIGN_MEMBER_COUNT = "GET_CAMPAIGN_MEMBER_COUNT";

// Campaign Guarantees
// Campaign Guarantees
export const GET_ALL_CAMPAIGN_GUARANTEES = "GET_ALL_CAMPAIGN_GUARANTEES";
export const GET_ALL_CAMPAIGN_GUARANTEES_SUCCESS = "GET_ALL_CAMPAIGN_GUARANTEES_SUCCESS";
export const GET_ALL_CAMPAIGN_GUARANTEES_FAIL = "GET_ALL_CAMPAIGN_GUARANTEES_FAIL";

// Add Campaign Guarantee
export const ADD_NEW_CAMPAIGN_GUARANTEE = "ADD_NEW_CAMPAIGN_GUARANTEE";
export const ADD_NEW_CAMPAIGN_GUARANTEE_SUCCESS = "ADD_NEW_CAMPAIGN_GUARANTEE_SUCCESS";
export const ADD_NEW_CAMPAIGN_GUARANTEE_FAIL = "ADD_NEW_CAMPAIGN_GUARANTEE_FAIL";

// Edit Campaign Guarantee
export const UPDATE_CAMPAIGN_GUARANTEE = "UPDATE_CAMPAIGN_GUARANTEE";
export const UPDATE_CAMPAIGN_GUARANTEE_SUCCESS = "UPDATE_CAMPAIGN_GUARANTEE_SUCCESS";
export const UPDATE_CAMPAIGN_GUARANTEE_FAIL = "UPDATE_CAMPAIGN_GUARANTEE_FAIL";

// Delete Campaign Guarantee
export const DELETE_CAMPAIGN_GUARANTEE = "DELETE_CAMPAIGN_GUARANTEE";
export const DELETE_CAMPAIGN_GUARANTEE_SUCCESS = "DELETE_CAMPAIGN_GUARANTEE_SUCCESS";
export const DELETE_CAMPAIGN_GUARANTEE_FAIL = "DELETE_CAMPAIGN_GUARANTEE_FAIL";

// Campaign Guarantee Details
export const GET_CAMPAIGN_GUARANTEE_DETAILS = "GET_CAMPAIGN_GUARANTEE_DETAILS";
export const GET_CAMPAIGN_GUARANTEE_COUNT = "GET_CAMPAIGN_GUARANTEE_COUNT";


// Campaign Guarantees
// Campaign Attendeees
export const GET_CAMPAIGN_ATTENDEES = "GET_CAMPAIGN_ATTENDEES";
export const GET_CAMPAIGN_ATTENDEES_SUCCESS = "GET_CAMPAIGN_ATTENDEES_SUCCESS";
export const GET_CAMPAIGN_ATTENDEES_FAIL = "GET_CAMPAIGN_ATTENDEES_FAIL";

// Add Campaign Attendeees
export const ADD_NEW_CAMPAIGN_ATTENDEE = "ADD_NEW_CAMPAIGN_ATTENDEE";
export const ADD_NEW_CAMPAIGN_ATTENDEE_SUCCESS = "ADD_NEW_CAMPAIGN_ATTENDEE_SUCCESS";
export const ADD_NEW_CAMPAIGN_ATTENDEE_FAIL = "ADD_NEW_CAMPAIGN_ATTENDEE_FAIL";

// Edit Campaign Attendeees
export const UPDATE_CAMPAIGN_ATTENDEE = "UPDATE_CAMPAIGN_ATTENDEE";
export const UPDATE_CAMPAIGN_ATTENDEE_SUCCESS = "UPDATE_CAMPAIGN_ATTENDEE_SUCCESS";
export const UPDATE_CAMPAIGN_ATTENDEE_FAIL = "UPDATE_CAMPAIGN_ATTENDEE_FAIL";

// Delete Campaign Attendeees
export const DELETE_CAMPAIGN_ATTENDEE = "DELETE_CAMPAIGN_ATTENDEE";
export const DELETE_CAMPAIGN_ATTENDEE_SUCCESS = "DELETE_CAMPAIGN_ATTENDEE_SUCCESS";
export const DELETE_CAMPAIGN_ATTENDEE_FAIL = "DELETE_CAMPAIGN_ATTENDEE_FAIL";

// Campaign Attendeees Details
export const GET_CAMPAIGN_ATTENDEE_DETAILS = "GET_CAMPAIGN_ATTENDEE_DETAILS";
export const GET_CAMPAIGN_ATTENDEE_COUNT = "GET_CAMPAIGN_ATTENDEE_COUNT";


// Campaign Sorting
export const GET_ALL_CAMPAIGN_SORTING = "GET_ALL_CAMPAIGN_SORTING";
export const GET_CAMPAIGN_COMMITTEE_SORTING = "GET_CAMPAIGN_COMMITTEE_SORTING";
