// Group Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

// Get Groups
export const GET_GROUPS = "GET_GROUPS";
export const GET_MODERATOR_GROUPS = "GET_MODERATOR_GROUPS";

// Add Group
export const ADD_NEW_GROUP = "ADD_NEW_GROUP";
export const ADD_NEW_GROUP_SUCCESS = "ADD_NEW_GROUP_SUCCESS";
export const ADD_NEW_GROUP_FAIL = "ADD_NEW_GROUP_FAIL";

// Edit Group
export const UPDATE_GROUP = "UPDATE_GROUP";
export const UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS";
export const UPDATE_GROUP_FAIL = "UPDATE_GROUP_FAIL";

// Delete Group
export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_FAIL = "DELETE_GROUP_FAIL";
