// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_ALL_ATTENDEES = "GET_ALL_ATTENDEES";

// Add Attendee
export const ADD_NEW_ATTENDEE = "ADD_NEW_ATTENDEE";
export const ADD_ATTENDEE_SUCCESS = "ADD_ATTENDEE_SUCCESS";
export const ADD_ATTENDEE_FAIL = "ADD_ATTENDEE_FAIL";

// Edit Attendee
export const UPDATE_ATTENDEE = "UPDATE_ATTENDEE";
export const UPDATE_ATTENDEE_SUCCESS = "UPDATE_ATTENDEE_SUCCESS";
export const UPDATE_ATTENDEE_FAIL = "UPDATE_ATTENDEE_FAIL";

// Delete Attendee
export const DELETE_ATTENDEE = "DELETE_ATTENDEE";
export const DELETE_ATTENDEE_SUCCESS = "DELETE_ATTENDEE_SUCCESS";
export const DELETE_ATTENDEE_FAIL = "DELETE_ATTENDEE_FAIL";
