# Generated by Django 4.2.2 on 2023-11-29 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSortingMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'منشور'), (2, 'خاص'), (3, 'في أنتظار الموافقة'), (4, 'يفتقد للبيانات'), (5, 'جاري العمل عليه'), (6, 'جديد'), (9, 'محذوف')], null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(3, 'عالي'), (2, 'متوسط'), (1, 'منخفض')], null=True)),
                ('moderators', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorting_elections', to='elections.election')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorting_election_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election Sorting',
                'verbose_name_plural': 'Election Sortings',
                'db_table': 'electionSorting',
                'permissions': [('canViewElectionSorting', 'Can View Election Sorting'), ('canAddElectionSorting', 'Can Add Election Sorting'), ('canChangeElectionSorting', 'Can Change Election Sorting'), ('canDeleteElectionSorting', 'Can Delete Election Sorting')],
                'default_permissions': [],
            },
        ),
    ]
