# Generated by Django 4.2.2 on 2023-11-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_electionsortingmembers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='electionsortingmembers',
            table='election_sorting_members',
        ),
    ]
