# Generated by Django 4.2.2 on 2024-01-15 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0008_rename_election_committee_sorter_electioncommittee_sorter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('election_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_candidate_sortings', to='elections.electioncandidate')),
                ('election_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_election_committees', to='elections.electioncommittee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election Sorting',
                'verbose_name_plural': 'Election Sortings',
                'db_table': 'election_sorting',
                'permissions': [('canViewElectionSorting', 'Can View Election Sorting'), ('canAddElectionSorting', 'Can Add Election Sorting'), ('canChangeElectionSorting', 'Can Change Election Sorting'), ('canDeleteElectionSorting', 'Can Delete Election Sorting')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionPartySorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('election_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_election_committees', to='elections.electioncommittee')),
                ('election_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_election_party_sortings', to='elections.electionparty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election Party Sorting',
                'verbose_name_plural': 'Election Party Sortings',
                'db_table': 'election_party_sorting',
                'permissions': [('canViewElectionSorting', 'Can View Election Sorting'), ('canAddElectionSorting', 'Can Add Election Sorting'), ('canChangeElectionSorting', 'Can Change Election Sorting'), ('canDeleteElectionSorting', 'Can Delete Election Sorting')],
                'abstract': False,
            },
        ),
    ]
