# Generated by Django 4.2.2 on 2024-03-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_alter_electioncommitteeresult_election_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionpartycandidatecommitteeresult',
            name='election_candidate',
        ),
        migrations.RemoveField(
            model_name='electionpartycommitteeresult',
            name='election_candidate',
        ),
        migrations.AlterField(
            model_name='election',
            name='election_method',
            field=models.CharField(blank=True, choices=[('candidateOnly', 'Candidate Only System'), ('partyOnly', 'Party Only System'), ('partyCandidateOnly', 'Party Candidate Only System'), ('partyCandidateCombined', 'Combined Party Candidate System'), ('proportionalRepresentationSystem', 'Proportional Representation System'), ('mixedElectoralSystem', 'Mixed Electoral System')], max_length=50, null=True, verbose_name='Election Type'),
        ),
        migrations.AlterField(
            model_name='electionpartycandidatecommitteeresult',
            name='election_party_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_candidate_committee_result_candidates', to='elections.electionpartycandidate'),
        ),
        migrations.AlterField(
            model_name='electionpartycommitteeresult',
            name='election_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_committee_result_candidates', to='elections.electionparty'),
        ),
    ]
